Updated TargetFrameworkVersions to match Cake 3.0.0 versions.
cake-contrib/CakeContrib.Guidelines pull request #218
Opened 2022-11-11 14:46 UTC by squid-box

As noted in #217, the supported frameworks needs to be updated following the release of Cake 3.0.0.

As best as I can tell, this is what was necessary to change - and local tests at least work with the version produced with my changes. I'm very much open to feedback on this, should I have missed/misunderstood something.

2022-11-11 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cake-contrib/CakeContrib.Guidelines?pullRequest=218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cake-contrib/CakeContrib.Guidelines?pullRequest=218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cake-contrib/CakeContrib.Guidelines?pullRequest=218) it.</sub>

2022-11-11 19:23 UTC, nils-a commented
Thanks for working on this. 👍

Looks good at first glance, I'll have a closer look when I can get to a computer.

2022-11-11 19:34 UTC, nils-a commented
@squid-box would you also be in a position to update the docs?

https://github.com/cake-contrib/CakeContrib.Guidelines/blob/develop/docs/input/guidelines/TargetFramework.md#L29-L40

(Seems I missed those for the 2.0.0 version, too. 😇)

2022-11-11 20:47 UTC, squid-box commented
@nils-a: I'm really moving into dangerous territory here, documenting something I'm very vaguely understanding 😄 - but I've made an attempt.

I'm not sure if there also needs to be an update to the module version checks for 3.0.0, they're untouched so far (but I did update their documentation as well, for better or worse).

2022-11-12 18:21 UTC, nils-a commented
> I'm really moving into dangerous territory here, documenting something I'm very vaguely understanding

I'll guide you, I promise 😆 

> I'm not sure if there also needs to be an update to the module version checks...

Yes, I'll add some comments to changes you made to the docs. The implementation should reflect that accordingly.

I'll have access to a decent computer (rather: keyboard and monitor) on Monday if you need more help than I can provide via mobile.

2022-11-12 20:23 UTC, nils-a requested changes

2022-11-12 20:23 UTC, nils-a commented on docs/input/guidelines/TargetFramework.md
> +    * Required: `netcoreapp3.1`
```suggestion
  * Cake.Core < 2.0.0
    * Required: `netstandard2.0`
  * Cake.Core >= 2.0.0
    * Required: `netcoreapp3.1`
  * Cake.Core >= 3.0.0
    * Required: `net6.0`
```

Starting from Cake.Core 3.0.0 the suggestion is to target `net6.0` for modules.

2022-11-13 22:15 UTC, nils-a approved these changes

2022-11-14 08:01 UTC, nils-a commented
@squid-box Perfect. Thanks for getting this done.

I have fixed up the commits a bit (hope you don't mind) and added one additional change (CCG0009 - Suggested Cake version to use)

2022-11-14 08:05 UTC, merged

2022-11-14 08:10 UTC, nils-a commented
@squid-box your changes have been merged, thanks for your contribution :+1:

2022-11-14 09:34 UTC, nils-a commented
@all-contributors please add @squid-box for code.